# Generated by Django 3.0.5 on 2020-04-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('S', 'Sold'), ('R', 'Restocking')], default='S', max_length=10),
        ),
    ]
